packaging_format = 2

id = "linkstack"
name = "LinkStack"
description.en = "A highly customizable link sharing platform with an intuitive, easy to use user interface."
description.fr = "Une plateforme de partage de lien hautement personnalisable, avvec une interface simple à utiliser."

version = "3.6.0~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "agpl-3-or-later"
website = "https://linkstack.org/"
admindoc = "https://docs.linkstack.org/"
code = "https://some.forge.com/example/example"
# FIXME: No CPE yet... check https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=LinkStack
#cpe = "???"
fund = "https://liberapay.com/LittleLink-Custom"

[integration]
yunohost = ">= 11.1.14"
architectures = "all"
multi_instance = true
ldap = "false"
sso = "false"
# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    type = "password"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

        [resources.sources.main]
        # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
        #    ynh_setup_source --dest_dir="$install_dir"
        # You can also define other assets than "main" and add --source_id="foobar" in the previous command
        url = "https://github.com/LinkStackOrg/LinkStack/releases/download/v3.6.0/linkstack.zip"
        sha256 = "af8ee7968138971ffc86fbcc8021031e68048881f0a0f78426780d0eda072c46"

        # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
        # to auto-update the previous asset urls and sha256sum + manifest version
        # assuming the upstream's code repo is on github and relies on tags or releases
        # See the 'sources' resource documentation for more details

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "linkstack.zip"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "php8.1-bcmath php8.1-curl php8.1-mbstring php8.1-xml php8.1-sqlite3"
