packaging_format = 2

id = "linkstack"
name = "LinkStack"
description.en = "Highly customizable link sharing platform"
description.fr = "Plateforme de partage de lien hautement personnalisable"

version = "4.8.4~ynh2"

maintainers = ["Tagada", "wyverine"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://linkstack.org/"
admindoc = "https://docs.linkstack.org/"
code = "https://github.com/LinkStackOrg/LinkStack"
fund = "https://liberapay.com/LinkStack"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"
    help.en = "The email address of this user will be used as the admin login for LinkStack"
    help.fr = "L'adresse e-mail associée à cet utilisateur sera utilisée comme identifiant administrateur dans LinkStack"

    [install.password]
    type = "password"
    help.en = "The password for the LinkStack admin user"
    help.fr = "Le mot de passe pour le compte administrateur de LinkStack"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/LinkStackOrg/LinkStack/releases/download/v4.8.4/linkstack.zip"
        sha256 = "28519378b1e893da024d4910002d5638e06bc3cc1cde334dbec48898d23240ad"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "linkstack.zip"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.4-bcmath php8.4-curl php8.4-imagick php8.4-mbstring php8.4-xml php8.4-sqlite3"
