#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=10M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_write_var_in_file --file="$install_dir/.env" --key="MAINTENANCE_MODE" --value="true"

ynh_setup_source --dest_dir="$install_dir" --keep=".env database/database.sqlite"

# Remove this file as the app is already installed
ynh_safe_rm $install_dir/INSTALLING

chmod o-rwx "$install_dir" -R

# Disable maintenance mode
ynh_write_var_in_file --file="$install_dir/.env" --key="MAINTENANCE_MODE" --value="false"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
